# Generated by Django 5.2.7 on 2025-10-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationotp',
            name='verify_type',
            field=models.CharField(choices=[('register', 'Register'), ('reset_password', 'Reset password')], default='register', max_length=14, verbose_name='Verification type'),
        ),
    ]
