# Generated by Django 5.2.7 on 2025-10-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verificationotp_verify_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
